name: OWASP ZAP API Scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Log Aggregator
        run: |
          go run ./cmd/aggregator &
          sleep 5
          
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          format: openapi
          schema: './docs/openapi.yaml'
          fail_action: false
